version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqaGit8JulyProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SiqaGit8JulyProject
  gitUsername: siqagituser
  gitBranch: main
